name: GitHub Pages

on:
  push:
    tags: ["*"]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: yarn build
      - run: "echo 'converter.zazuko.com' > dist/CNAME"
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
